// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	domain "billing-engine/internal/modules/billing/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BillingUsecase is an autogenerated mock type for the BillingUsecase type
type BillingUsecase struct {
	mock.Mock
}

// BillingRepayment provides a mock function with given fields: ctx, data
func (_m *BillingUsecase) BillingRepayment(ctx context.Context, data *domain.RequestBillingRepayment) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for BillingRepayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RequestBillingRepayment) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBillingUsecase creates a new instance of BillingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingUsecase {
	mock := &BillingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
