version: "3"

services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - app-network

  redis:
    image: 'redis:4-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    restart: on-failure
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
